name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubunto-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with: 
          who-to-greet: Abir
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.Time}}"